-- Apply only to the dedicated HRBIP database. No local data is copied.
BEGIN;
CREATE SCHEMA IF NOT EXISTS hrbip;
REVOKE ALL ON SCHEMA hrbip FROM PUBLIC;
SET LOCAL search_path = hrbip, public;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY, username TEXT UNIQUE NOT NULL, password TEXT NOT NULL, created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS works(id TEXT PRIMARY KEY,owner TEXT NOT NULL REFERENCES users(id),title TEXT NOT NULL,payload TEXT NOT NULL,updated TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS originals(id TEXT NOT NULL,work_id TEXT NOT NULL REFERENCES works(id) ON DELETE CASCADE,name TEXT NOT NULL,data BYTEA NOT NULL,PRIMARY KEY(id,work_id));
CREATE TABLE IF NOT EXISTS shares(work_id TEXT NOT NULL REFERENCES works(id) ON DELETE CASCADE,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,PRIMARY KEY(work_id,user_id));
CREATE TABLE IF NOT EXISTS templates(id TEXT PRIMARY KEY,owner TEXT NOT NULL REFERENCES users(id),title TEXT NOT NULL,payload TEXT NOT NULL,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS requests(id TEXT PRIMARY KEY,body TEXT NOT NULL,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS company_formats(id TEXT PRIMARY KEY,owner TEXT NOT NULL REFERENCES users(id),title TEXT NOT NULL,format TEXT NOT NULL,version INTEGER NOT NULL,created TEXT NOT NULL,payload TEXT NOT NULL,data BYTEA NOT NULL);
CREATE INDEX IF NOT EXISTS sessions_expiry ON sessions(expires);
CREATE INDEX IF NOT EXISTS works_owner ON works(owner);
CREATE INDEX IF NOT EXISTS shares_user ON shares(user_id);
CREATE INDEX IF NOT EXISTS formats_owner ON company_formats(owner);
REVOKE ALL ON ALL TABLES IN SCHEMA hrbip FROM PUBLIC;
-- Service SQL credentials stay on the backend. This schema is not a browser API.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE works ENABLE ROW LEVEL SECURITY;
ALTER TABLE originals ENABLE ROW LEVEL SECURITY;
ALTER TABLE shares ENABLE ROW LEVEL SECURITY;
ALTER TABLE templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_formats ENABLE ROW LEVEL SECURITY;
COMMIT;
